[package]
name = "purewasm-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = { workspace = true, default-features = false }
serde = { workspace = true, default-features = false }
purewasm-core = {  path = "../../../core" }

