[workspace]
members = [
    "crates/core",
    "crates/event",
    "crates/alloc",
    "crates/bindgen",
    "crates/wasmid"
]
exclude = ["examples/*"]

[profile.release]
lto = true
opt-level = "z"
strip = "symbols"