[package]
name = "purewasm"
edition = "2021"
description = "Pure WASM bindings"
version = "0.1.0"
authors = ["Idp2p <adem.caglin@gmail.com>"]
license = "APACHE 2.0"
repository = "https://github.com/purewasm/rust-purewasm"
readme = "README.md"
keywords = ["idp2p", "wasm", "webassembly", "purewasm"]
categories = ["webassembly"]

[workspace]
members = [
    "core",
    "codec/cbor",
    "codec/json",
    "bindgen",
    "runtime/wasmtime"
]

[features]
bindgen = ["purewasm-bindgen/cbor"]
bindgen-json = ["purewasm-bindgen/json"]
wasmtime = ["purewasm-wasmtime"]

[dependencies]
purewasm-core = { path = "core" }
purewasm-bindgen = { path = "bindgen", optional = true }
purewasm-wasmtime = { path = "runtime/wasmtime", optional = true }

[workspace.dependencies]
serde = { version = "1.0.188", default-features = false, features = ["derive", "alloc"] }

