[package]
name = "purewasm"
edition = "2021"
description = "Pure WASM bindings"
version = "0.1.0"
authors = ["adem caglin<adem.caglin@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/purewasm/rust-purewasm"
readme = "README.md"
keywords = ["idp2p", "wasm", "webassembly", "purewasm"]
categories = ["webassembly"]

[workspace]
members = [
    "bindgen/codec/cbor",
    "bindgen/codec/json",
    "bindgen",
    "runtime/wasmtime",
    "examples/module"
]

[features]
bindgen = ["purewasm-bindgen"]
bindgen-cbor = ["dep:purewasm-cbor"]
bindgen-json = ["dep:purewasm-json"]
wasmtime = ["purewasm-wasmtime"]

[profile.release]
lto = true
opt-level = "z"
strip = "symbols"

[dependencies]
purewasm-cbor = { workspace = true, optional = true }
purewasm-json = { workspace = true, optional = true }
purewasm-bindgen = { workspace = true, optional = true }
purewasm-wasmtime = { workspace = true, optional = true }
cfg-if = "1.0.0"

[workspace.dependencies]
serde = { version = "1.0.188", default-features = false, features = ["derive", "alloc"] }
purewasm-proc-macro = { path = "bindgen/proc-macro", version = "0.1.0" }
purewasm-cbor = { path = "bindgen/codec/cbor", version = "0.1.0" }
purewasm-json = { path = "bindgen/codec/json", version = "0.1.0" }
purewasm-bindgen = { path = "bindgen", version = "0.1.0" }
purewasm-wasmtime = { path = "runtime/wasmtime", version = "0.1.0" }

