[workspace]
members = [
    "codec",
    "bindgen",
    #"crates/model",
    #"crates/crypto",
    #"crates/misc",
    "core",
    "examples/wasmid"
]
#exclude = ["examples/*"]

[workspace.dependencies]
sha2 = { version = "0.10.7", default-features = false }
serde = { version = "1.0.188", default-features = false, features = ["derive", "alloc"] }

[profile.release]
lto = true
opt-level = "z"
strip = "symbols"