[package]
name = "purewasm-bindgen"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
lol_alloc = "0.4.0"
proc-macro = { path = "proc-macro" }
purewasm-core = { path = "../core" }
serde = { workspace = true, default-features = false, features = [
    "derive",
    "alloc",
] }

