[package]
name = "purewasm-bindgen"
version = "0.1.0"
edition = "2021"

[dependencies]
purewasm-bindgen-proc-macro= { path = "proc-macro" }
purewasm-core= { path = "../core" }
lol_alloc = "0.4.0"
serde = { workspace = true, default-features = false, features = ["derive", "alloc"] }

[dev-dependencies]
purewasm-bindgen = { path = "."}
purewasm-codec= { path = "../codec", features = ["cbor"] }
