[package]
name = "purewasm-bindgen"
version = "0.1.0"
edition = "2021"

[dependencies]
lol_alloc = "0.4.0"
proc-macro = { path = "proc-macro" }
purewasm-core = { path = "../core" }
purewasm-cbor = { path = "../codec/cbor", optional = true }
purewasm-json = { path = "../codec/json", optional = true }
serde = { workspace = true, default-features = false, features = [
    "derive",
    "alloc",
] }

[features]
default = ["cbor"]
cbor = ["dep:purewasm-cbor"]
json = ["dep:purewasm-json"]
