[package]
name = "purewasm-misc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, default-features = false, features = ["derive", "alloc"] }
serde_bytes = { version = "0.11.12", default-features = false, features=["alloc"] }
