[package]
name = "purewasm-simple-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
purewasm = { path = "../../../", features = ["wasmtime"] }
purewasm-cbor = { path = "../../../codec/cbor" }
purewasm-simple-core = { path = "../core" }
