[package]
name = "purewasm-simple-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
purewasm-core = { path = "../../../core" }
purewasm-cbor = { path = "../../../codec/cbor" }
purewasm-wasmtime = { path = "../../../runtime/wasmtime" }
purewasm-simple-shared = { path = "../shared" }
