[package]
name = "purewasm-simple-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "12.0.1"
purewasm-core = { version = "0.1.0", path = "../../../crates/core", features = ["cbor"]}
purewasm-simple-shared = { version = "0.1.0", path = "../shared" }