[package]
name = "purewasm-simple-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "12.0.1"
purewasm-core = { path = "../../../core" }
purewasm-codec = { path = "../../../codec", features = ["cbor"]}
purewasm-simple-shared = { path = "../shared" }