[package]
name = "purewasm-simple-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
purewasm-model = { path = "../../../crates/model" }
serde = { version = "1.0.188", default-features = false, features = ["derive", "alloc"] }

