[package]
name = "wasmid"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
opt-level = "z"
strip = "symbols"

[lib]
crate-type = ["cdylib"]

[dependencies]
purewasm-bindgen = {path = "../../bindgen" }
wasmid-core = { path = "core" }